### ISSUE TITLE
English Version

### ISSUE THREAD

**Issue by BenIpinge** [java110/MicroCommunity#19]
I found your software while searching for open source community property management software. I would like to request or find out whether you have an english version of the software?

**Comment by 928255095** [comment]
now we have Chinese version,

**Comment by BenIpinge** [comment]
I can see that, but are you planning on releasing an english version?

**Comment by 928255095** [comment]
yes

**Comment by BenIpinge** [comment]
Awesome, when do you think it will be available?

**Comment by 928255095** [comment]
> Awesome, when do you think it will be available?

now it's ok
